export { TabsPageModule } from './tabs/tabs.module';
export { TabsPatientPageModule } from './tabsPatient/tabsPatient.module';
export { LoginModule } from './pages/login/login.module';
export { HomeAModule } from './pages/admin/home-a/home-a.module';
export { HomePModule } from './pages/patient/home-p/home-p.module';
import { PatientsAModule } from './pages/admin/patients-a/patients-a.module';
import { DentistsAModule } from './pages/admin/dentists-a/dentists-a.module';
import { SuppliesAModule } from './pages/admin/supplies-a/supplies-a.module';
import { ServicesAModule } from './pages/admin/services-a/services-a.module';
import { InventoryAModule } from './pages/admin/inventory-a/inventory-a.module';
import { HomeDModule } from './pages/dentist/home-d/home-d.module';
import {AppointmentsAModule } from './pages/admin/appointments-a/appointments-a.module';
import {AppointmentsDModule } from './pages/dentist/appointments-d/appointments-d.module';
import {AppointmentsPModule } from './pages/patient/appointments-p/appointments-p.module';
import {ServicesPModule } from './pages/patient/services-p/services-p.module';
import { AccountPModule } from './pages/patient/account-p/account-p.module';